### ISSUE TITLE
Баги бойлеров Грега.

### ISSUE THREAD

**Issue by Pilad** [Nukepowered/GregTech4#102]
Баги с бойлерами:
1. Если использовать универсальные капсулы с водой, то бойлер наполняется только если закидывать по 1 капсуле. Стак не опустошается.
2. Если использовать пузырёк с водой, то он опустошается, но внутренний буфер бойлера не наполняется.
3. Если не стоит рэилкрафт или иной мод ,что может генерировать пар, бойлер не генерирует пар. У индастриалкрафта пар обычный не совместим с паром того же рэилкрафта.
4. Насколько заметил по коду у бойлера бронзового и стального одинаковые значения генерации пара. Вероятно стоит увеличить ему выработку как и внутренние буфера для воды и пара и т.д.

**Comment by TheDarkDnKTv** [comment]
Неправильно оформлена проблема. Все проблемы должны быть открыты индивидуально.

1. Проверю, возможно ошибка.
2. Разумеется, ибо у пузырька нет явного значения кол-ва жидкости.
3. В случае отсутствия мода с паром, должен вырабатываться пар IC2. А то что он не потребляется механизмами из других модов - не проблема GT.
4. Не уверен, проверю.

**Comment by Pilad** [comment]
Пар у индастриала совершенно другой, он вроде даже ТЕ. И его другие моды не могут вообще использовать. И при наличии только индастриала в гуи бойлера полоска пара даже и не заполняется. На пятом греге нет такой проблемы , если только есть грег и индастриал, бойлера нормально генерят обычный пар подобный рэилкрафтовскому. А насчет пузырька с водой, то на 1.6.4 он вроде нормально заполнял бойлер. Пузырёк считался вроде равный 1000мб.

**Comment by TheDarkDnKTv** [comment]
По поводу пара - ic2 пар другой так как его registery name `ic2steam` а не steam. Так как в коде не было регистрации своей жидкости пара с обычным регистри именем, то и добавлять я её не буду. Опять же в коде с версии 1.6.4 так и было, что при отсутствии пара под именем `steam` подавался пар из ic2.

**Comment by Pilad** [comment]
На 1.6.4 в индастриале вроде и не было пара. Там же нет кинетических паровых генераторов как и парового котла. Там только зачатки жидкостного реактора были. 
А стержни на тории добавите? А то он есть, а использования нет.

**Comment by Pilad** [comment]
Хотя я не вижу рецептов топливных стержней на уране и на моксе. Видать рецепты на удаление прописаны, а на добавление через наполнитель что-то отвалились.

**Comment by TheDarkDnKTv** [comment]
Все обсуждения в дальнейшем пожалуйста перенесите в наш дискорд, там есть специальный канал для этого. 
p.s проверил рецепты стержней реактора - их действительно нет.
