### ISSUE TITLE
Suggestion: nikolite to electrotine.

### ISSUE THREAD

**Issue by DbpGaming** [Nukepowered/GregTech4#108]
Nikolite is pretty much useless without redpower existing on this version, compatiblity with projectred and bluepower would be nice, sort of how it makes peridot from projectred compatible with olivine

**Comment by TheDarkDnKTv** [comment]
I will check compat, then may add duplicate material which copies Nikolite. Since we DO need nikolite support ;)

**Comment by DbpGaming** [comment]
Yeah I'm not saying change the material just adding electrotine and teslatite oredicts, an extra material is probably not needed

**Comment by TheDarkDnKTv** [comment]
Electortine as generated and handled material been added.
