### ISSUE TITLE
NEI Render Bug

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#112]
Fluid slots in NEI recipes are rendered like this when x32 resource-pack is applied (haven't tried with >32 resolution) 

<details>
  <summary>Vanilla x16 resource:</summary>
  
![2021-04-23 (4)](https://user-images.githubusercontent.com/25727222/115898483-47040f80-a466-11eb-9b74-0aea37f2a96d.png)

</details>

<details>
  <summary>Faithful x32 resource:</summary>
  
![2021-04-23 (5)](https://user-images.githubusercontent.com/25727222/115898099-d65cf300-a465-11eb-9f57-8a9a6b197f71.png)

![image](https://user-images.githubusercontent.com/25727222/115898143-e543a580-a465-11eb-91c2-9f0d6d8993c4.png)

![image](https://user-images.githubusercontent.com/25727222/115898171-ed9be080-a465-11eb-9695-51d959975972.png)

![image](https://user-images.githubusercontent.com/25727222/115898226-fb516600-a465-11eb-9a8d-87b86c447e04.png)

![image](https://user-images.githubusercontent.com/25727222/115898238-ff7d8380-a465-11eb-99e2-2d9b8781bc95.png)

</details>

**Comment by TheDarkDnKTv** [comment]
Lmao, not only in NEI
