### ISSUE TITLE
Config option doesn't seem to work 

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#114]
smallerWoodToolDurability option affects wooden tools, except wooden pickaxe.
![image](https://user-images.githubusercontent.com/25727222/115996354-9160ca00-a5e7-11eb-8972-9d78226b059c.png)
![image](https://user-images.githubusercontent.com/25727222/115996369-9b82c880-a5e7-11eb-919c-d80e8d3e870b.png)
![image](https://user-images.githubusercontent.com/25727222/115996385-a63d5d80-a5e7-11eb-8c45-5c2e75f3df6f.png)
![image](https://user-images.githubusercontent.com/25727222/115996392-af2e2f00-a5e7-11eb-9eed-35e3f666de2d.png)

Config:
```
    B:smallerStoneToolDurability=true
    B:smallerWoodToolDurability=true
```

GT: gregtechmod-v414.25 (.24 too)

Log: [latest.log](https://paste.ubuntu.com/p/XhnYshZsM7/) - pastebin link

UPD: With stone tools works as intended.

**Comment by TheDarkDnKTv** [comment]
It works. 

With disabled option
![image](https://user-images.githubusercontent.com/42381105/116008562-e3bcdd80-a61d-11eb-81e7-52d409c0987b.png)

With enabled:
![image](https://user-images.githubusercontent.com/42381105/116008581-f20af980-a61d-11eb-8044-de18949f0dcc.png)

`P.S I will recomend you to update your Java, update 51 is pretty old, some stuff would work wrong.`

**Comment by CrossVas** [comment]
Actually, I was talking about Wooden Pickaxe, not Wooden Shovel 🤔

**Comment by TheDarkDnKTv** [comment]
Lmao, there was typo in names, it was nerfing stone pickaxe twice....
