### ISSUE TITLE
Question about recipes

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#115]
I've noticed that recipes for both vanilla and IC2-vanilla (less) have no GT-equivalent. I know that IC2 recipes can be disabled via config. If so, there should be an alternative GT-recipe if you decide to disable them. So I was wondering, should these recipes be reported here to be fixed? Are they still WIP? What's the best and convenient way for you to report them?  Like, report them all-in-one-style issue or sort them by mod?

**Comment by TheDarkDnKTv** [comment]
Most of needed recipe are replaced by GT. Other recipes not needed for GT/okay. So you can manually disable IC2 machine recipes, if you wish.

**Comment by CrossVas** [comment]
Would you mind if I'll do a full check over GT4 1.6.4 and 1.7.10 versions to compare them and report back here without creating another issue?

**Comment by TheDarkDnKTv** [comment]
You are welcome

**Comment by CrossVas** [comment]
Recipes that shouldn't have a shaped crafting recipe by default:
Vanilla:
- Redstone Block (not following Compressor rule)
- Block of Quartz (?) - 4 quartz -> 1 block in Compressor
TE: 
- Alloy Smelter - Bronze Recipe
- Alloy Smelter - GT Red Alloy Ingot
Project Red:
- Remove Red Alloy Ingot recipe or make it them irreplaceable, otherwise Steam Alloy Smelter is useless at early game
Thermal Foundation and Forestry:
- Cheap metal Gears - could be a case o choice for every player, not sure about them.

Recipes that shouldn't be valid by default, but could be disabled via config:
IC2:
- Solar Panel;
- Both Electronic circuits 
- Mixed Metal Ingot

Recipes that should be added:
- Assembler: 8 any type of stone (incl. GT) + 1 reinforced plate = 8 reinforced stone
- Recipes for Iron and Steel Shafts using lathe

**Comment by CrossVas** [comment]
The most critic, especially at early game, are recipes for alloys using TE's Smelter as well as GT red alloy being replaceable with PR one which is cheap as hell and don't require any machine, redstone block vanilla recipe and cheap gears.

**Comment by DbpGaming** [comment]
Cheap metal gears have been a thing in gt3/4 and in fact they are supposed to have assembler recipes but I think this misses them, everything else seems right

**Comment by TheDarkDnKTv** [comment]
> Remove Red Alloy Ingot recipe or make it them irreplaceable
Oh, i did not notest it since we using redpower 😄
