### ISSUE TITLE
OpenBlocks removes Iron Bars' GT recipe 

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#116]
As the title states, when OB is loaded, Iron Bars have no recipe. I couldn't find anything related to this in the log. 
Also it would be great to have an Assembly recipe for them :)

GT: gregtechmod-v414.25
Log: [latest](https://paste.ubuntu.com/p/8Jys7FrFWt/)

**Comment by TheDarkDnKTv** [comment]
lmao, i found this shit in my server aswell. It is not fault of OB, it just occues of magic. I rewrited code, but actually not changed its logic, but now its works. Closed in 5cc5ae8a7.
