### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#118]
All material items from GT aren't visible on Thermal Expansion's Cache. 
![image](https://user-images.githubusercontent.com/25727222/117207603-cbf30f80-adfc-11eb-9b0a-48d88428d05e.png)

**Comment by TheDarkDnKTv** [comment]
There is 99% TEs problem, meta items of GT has custom item renderer, so it should be called for render, not vanilla one. I will check it

**Comment by CrossVas** [comment]
I reported it to you, because from both involved mods, GT is the one who's still under development.

**Comment by TheDarkDnKTv** [comment]
Lmao, it is definitly TE problem. They are putting zLevel of render as 0.0, but in inventory it is 50. Also forge making some shitcode, so in render code is unable to define what is current zLevel. I will adjust it to render not inside a block. Btw in storage drawers its working fine.
![2021-05-06_01 54 59](https://user-images.githubusercontent.com/42381105/117219510-18931680-ae0e-11eb-9508-5ea777208473.png)
