### ISSUE TITLE
Industrial Grinder Get Stuck 

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#120]
Setup:

Minecraft: 1.7.10
Forge: 10.13.4.1614
IC2: industrialcraft-2-2.2.828-experimental
GregTech: gregtechmod-v414.25

Step to reproduce (using pipes): 
- Set up your Industrial Grinder
- Supply it with ores (I used Lapis Lazuli Ore for faster result)
- Extract outputs into a chest or buffer using pipes
- Wait until your buffer get filled (I used cobblestone to imitate smaller buffer)
- Wait until your grinder get filled
- Free up some space from buffer
- Pipes extracts outputs from grinder into your buffer
- Grinder get stuck

Step to reproduce (no other mods): 
- Set up your Industrial Grinder
- Supply it with ores 
- Wait until your grinder get filled
- Free up some space (grab some materials from output slots into your inventory)
- Grinder get stuck

Logs: 
[latest.log](https://paste.ubuntu.com/p/9VNWNV9Sph/) - pastebin link (starting from me entering my test world)

Demo:
[Click here](https://drive.google.com/file/d/1DYBkhcxALG8xFGoWQoc2tOEkmwux0F36/view?usp=sharing)

**Comment by TheDarkDnKTv** [comment]
It is hard to fix, you need to wait until machine will randomly check recipe. This occurs cause of shitcode on inventory updates, so cause of pipes machine do not know about inventory changed

**Comment by CrossVas** [comment]
Okay, so it seems like for now the only way to avoid this is to provide enough space for the outputs. Got you!

**Comment by TheDarkDnKTv** [comment]
Not quite i meant. This delay is ussualy small, machines checking recipe while IDLE once per 10 seconds, how i remember.
https://github.com/Nukepowered/GregTech4/blob/master/src/main/java/gregtechmod/api/recipe/RecipeLogic.java#L91

**Comment by CrossVas** [comment]
Yeah, I saw the code, but that's odd, because right now I'm in my test world where my grinder doesn't seem to start over his work after being stuck for like 20 minutes.

**Comment by CrossVas** [comment]
Rubber Hammer is your friend here. A right click with it solves the problem.

**Comment by TheDarkDnKTv** [comment]
```
Output overflow detected for machine (gregtechmod.common.tileentities.machines.multi.GT_MetaTileEntity_Grinder) left amount: 8, stack: 8xitem.GregTech_MetaGenerated_Item_01@1524
```
Also meet this in #123
