### ISSUE TITLE
Crash with gt6

### ISSUE THREAD

**Issue by DbpGaming** [Nukepowered/GregTech4#121]
My friend found a crash when loading this mod with gt6 similar to the other mod compat crashes I found before, https://pastebin.com/U5czT1r7

**Comment by TheDarkDnKTv** [comment]
Not compatible with others GTs.

**Comment by DbpGaming** [comment]
Doesn't seem like an issue with having the other gt but the recipe iteration, "Not compatible with other GTs" is a poor excuse when there's no reason other than recipes for it not to be

**Comment by TheDarkDnKTv** [comment]
Okay, but all this stuff is low priority for me now. If you would like, you can solve it by yourself. I may fix it, but will not promise when.

**Comment by DbpGaming** [comment]
No problem, I don't have a pc currently but I'm open to trying to fix it my self and doing prs at a later point in time

**Comment by TheDarkDnKTv** [comment]
Thank you very much for I spent 60 minutes of pure waiting until mc will load.
