### ISSUE TITLE
Crash on load with NetherOres and Another One Bites the Dust

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#125]
Setup: 
GT: gregtechmod-v415.32
IC2: industrialcraft-2-2.2.828-experimental
NetherOres: NetherOres-[1.7.10]2.3.1-22
CoFH Core: CoFHCore-[1.7.10]3.1.4-329
AOBD: AOBD-2.9.2

Crash report: [crash-report](https://paste.ubuntu.com/p/pRp4kcHN4f/) (external link)

Tags: An output ItemStack is null, AOBD, null, crash, crash on load, NetherOres

**Comment by TheDarkDnKTv** [comment]
Mmmmm, crushedPurifiedSteel.... Steel ore.... I seen enough.

**Comment by TheDarkDnKTv** [comment]
I get it fixed, but some recipes will have missing outputs (ex. Thermal centr. recipe of crushed steel ore, there is no centrifuged stack)
