### ISSUE TITLE
Crash with IC2 Classic

### ISSUE THREAD

**Issue by Plaxaris92** [Nukepowered/GregTech4#127]
Game crashes while loading.
Mods installed:
CodeChickenCore
NotEnoughItems
IC2 Classic
GregTech 4

Crash log: https://pastebin.com/5yh9eynk

If there is a config or something i have to change in order to make the game work properly, please let me know, thanks!

**Comment by TheDarkDnKTv** [comment]
This mod is developed for IC2Exp, IC2Classic not supported.
