### ISSUE TITLE
Crash with galacticraft on game load

### ISSUE THREAD

**Issue by DbpGaming** [Nukepowered/GregTech4#130]
https://pastebin.com/shAbgc2B

**Comment by TheDarkDnKTv** [comment]
Don't you like to say, without gt it is load fine? How can I see, there no installed some coremod.

**Comment by DbpGaming** [comment]
It's crashing because gt cannot find a galacticraft class (I'm assuming because galacticraft refactored a bit in 1.7)? Regardless I'll test galacticraft without gt and report back

**Comment by DbpGaming** [comment]
Without gt this issue does not occur

**Comment by TheDarkDnKTv** [comment]
I can't reproduce your problem. It's working fine if you install GT with it. Probably one of installed addons for galacticraft causes issue using ASM. Try install only gregtech and galacticraft. 

As proof of working:
![image](https://user-images.githubusercontent.com/42381105/122320171-83199500-cf2a-11eb-81aa-96a8c452754a.png)

**Comment by DbpGaming** [comment]
ok so its a triple mod issue, you need galacticraft, advanced solar panels, and gregtech 4 to have the crash

**Comment by TheDarkDnKTv** [comment]
> ok so its a triple mod issue, you need galacticraft, advanced solar panels, and gregtech 4 to have the crash

How I said: I cant reproduce this issue. It is definitly not problem of ASP, since we playing with it on out server. You need to find, mod that breaks load of galacticrafts class and report to their devs. It is not GT problem.
