### ISSUE TITLE
Missing config setting maybe

### ISSUE THREAD

**Issue by Redovec** [Nukepowered/GregTech4#133]
I just have a question. I play minecraft (especially modded) for a long time. I just found this mode and installed it. But I cant disable hard recipes (like iron chestplate from plates with hammer or make hopper from plates with hammer...). I hope we understand each other. And I tried change config file - just setting for saw. No setting on file, hammer, wrench... If I remember correctly these settings were in the old GregTech 4.

And what means this settings?
    B:disable_STDERR
    B:disable_STDOUT

**Comment by TheDarkDnKTv** [comment]
This cant be disabled since all meaning of GT is to _**harden**_ and extend default tech tree. 

> And what means this settings?
> B:disable_STDERR
> B:disable_STDOUT

This will disable console output streams (Error and default). If you dont know what is it - it is not for you.

**Comment by TheDarkDnKTv** [comment]
Also all this disscussion should be not on github, but on discord.
