### ISSUE TITLE
Stuck on Handling OreDict during Post Init

### ISSUE THREAD

**Issue by PaintsplattersMC** [Nukepowered/GregTech4#135]
On the loading screen with the red bars, GregTech4 becomes stuck on Handling OreDict on postinit  initialilizing mods phase 3

[latest.log](https://github.com/Nukepowered/GregTech4/files/6962145/latest.log)
[fml-client-latest.log](https://github.com/Nukepowered/GregTech4/files/6962149/fml-client-latest.log)

**Comment by DrParadox7** [comment]
You're running 350+ mods and the logs don't say a whole lot.
I recommend halving the mods loaded until you find the culprit.

**Comment by CrossVas** [comment]
OreDict Handling is not a quick process, it can take some time. Did you try to leave it so for a while to see if it passes postInit?

**Comment by TheDarkDnKTv** [comment]
Issue is incorrect, it  is not GT problem. Than more items/OreDict/Recipes you have, then longer process. On such big clients on loading you should not touch your PC at all, and may be your processor isnt powerfull enough. If you will switch window, java process can stuck. Had same issue on MC 1.12.2.

P.S finally github is up, was not able to comment.
