### ISSUE TITLE
Краши при использовании суперпроводников

### ISSUE THREAD

**Issue by meowNIman** [Nukepowered/GregTech4#144]
Суперпроводники регулярно вызывают полный отказ майна

**Comment by CrossVas** [comment]
Any way to reproduce this?

**Comment by meowNIman** [comment]
> Any way to reproduce this?

just play araound with them
they will cose it for certain i think that just placing them can cos crush as well 
but of course in more or less non simple shapes

**Comment by meowNIman** [comment]
![Uploading изображение.png…]()
i hade about 5-7 xrases while i was tring to place them
when i placed them i seems that they stoped crashing
also it hapens only when u place the block
