### ISSUE TITLE
ZPM не отдаёт энергию

### ISSUE THREAD

**Issue by meowNIman** [Nukepowered/GregTech4#145]
фиксится понижением его напряжения до 8192

**Comment by CrossVas** [comment]
Or you can use High Energy Charger: 
![image](https://user-images.githubusercontent.com/25727222/143725619-2c7d7ca1-6152-4e25-bb5c-96e15f35ca22.png)

**Comment by meowNIman** [comment]
> Or you can use High Energy Charger: ![image](https://user-images.githubusercontent.com/25727222/143725619-2c7d7ca1-6152-4e25-bb5c-96e15f35ca22.png)
yes u can
its the only way to use it
and imo its usless
so downgrading output to 8192 is acceptable
WDYT?

**Comment by CrossVas** [comment]
It's now useless, it is meant to be this way

**Comment by meowNIman** [comment]
agree, its not useless, but i assume that it should be changed according to IC-2 compobility 
so
ill close issue cos its not a bag
