### ISSUE TITLE
AESU вызывает взрывы машин

### ISSUE THREAD

**Issue by meowNIman** [Nukepowered/GregTech4#146]
AESU вызывает взрывы машин подключённых к ней напрямую ( без проводов)
вне зависимости от выбранного выхода энергии (даже при 0) и происходит это случайно вне зависимости от количества апгрейдов (трансформаторов)

**Comment by CrossVas** [comment]
This is because the AESU has a fixed tier value of 5. It shoul depend on the actual output.
