### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by meowNIman** [Nukepowered/GregTech4#149]
при создании литиевого энерго-ранца происходит мгновенный краш сервера.
![изображение](https://user-images.githubusercontent.com/79648109/139742420-91d2d71c-b4af-4939-834d-b099749a868a.png)

**Comment by meowNIman** [comment]
Следует этот предмет удалить из мода на совсем тк у него есть полная замена из IC-2

**Comment by meowNIman** [comment]
если принять мои изменения в батарейки. И эти изменения коснуться всех предметов, которые зависят от них, то этот ранец тоже перестанет быть бесполезным
[crash-2021-11-02_02.10.57-client.txt](https://github.com/Nukepowered/GregTech4/files/7456624/crash-2021-11-02_02.10.57-client.txt)

**Comment by CrossVas** [comment]
Minecraft fails to add crafting60kEuPack to oredict, so it is defaulting it to -1
