### ISSUE TITLE
Crash with Advanced Solar Panel and Galacticraft

### ISSUE THREAD

**Issue by TFCAliarcy** [Nukepowered/GregTech4#155]
[crash-2021-12-16_03.10.07-client.txt](https://github.com/Nukepowered/GregTech4/files/7725543/crash-2021-12-16_03.10.07-client.txt)

I've encountered a crash when using any version of your mod with AdvancedSolarPanel-1.7.10-3.5.1 and any version of Galacticraft after 1.7-3.0.12.396. This crash does not occur when using both AdvancedSolarPanels and Galacticraft or when Galacticraft and Gregtech. Only when all three are combined.

**Comment by TheDarkDnKTv** [comment]
Clone of #130
Check it, I've tried to work on this in past and found out it is Galacticraft/their addon ASM problem which can not be fixed from my side.
