### ISSUE TITLE
[1.7.10-4.15.36] Advanced Solar Panels compatibilty

### ISSUE THREAD

**Issue by SadScourge** [Nukepowered/GregTech4#157]
AESU and IDSU doesn't charge when connected to solar panel from Advanced Solar Panels
the solar panels empty their energy so it go somewhere but the AESU stay at 0 EU

btw nothing to do with this bug but the LESU got removed ?

version used:
gregtechmod-v415.36.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar

**Comment by CrossVas** [comment]
This is a problem with Advanced Solar Panels having their tier at Integer.MAX_VALUE which is not accepted by GT machines. 
Try this one - [AdvancedSolarPanels-1.7.10-3.5.1e.jar](https://drive.google.com/file/d/1JYWrmlQCY4OP9CvHL4Ee8ql5oclSOCSd/view?usp=sharing) 

My build should fix this issue as well as a couple of more fixes are included.
Note!! You'll have to re-gen your Advanced Solar main config file as now it has in-game GUI config support.

**Comment by SadScourge** [comment]
oh thank you for that it will be a game changer
