### ISSUE TITLE
Thick Neutron Reflector missing its gregified recipe

### ISSUE THREAD

**Issue by Ayliroe** [Nukepowered/GregTech4#164]
In IC2 experimental and with GT4 1.7.10:
![image](https://user-images.githubusercontent.com/106384472/170695417-f522eab0-0f77-4977-bd12-a407aaaf1ffc.png)

Expected (confirmed in GT4 1.6.2):
![image](https://user-images.githubusercontent.com/106384472/170695552-5b1a5b04-940e-46dd-a85b-7499e7bfe4d2.png)

Originally this would have been one of the only two uses for beryllium, I believe? (the other being for fusion reactions).

**Comment by meowNIman** [comment]
we are working on this one

**Comment by Ayliroe** [comment]
Also, there's a typo in the liquid form of Beryllium:
![image](https://user-images.githubusercontent.com/106384472/170720010-a5fc31ad-1ef2-4866-bbd2-f594d3e40729.png)
vs (only one 'l'):
![image](https://user-images.githubusercontent.com/106384472/170720137-a478d297-15b8-4dc3-b2e6-369583eb7c60.png)

But it basically has no impact whatsoever
