### ISSUE TITLE
Gregtech 4 for IC2 Classic

### ISSUE THREAD

**Issue by GabrielitoPL** [Nukepowered/GregTech4#166]
Greetings, this great gregtech 4 mod could be compatible with the IC2 Classic version of this same version 1.7.10, I don't know why there is no gregtech 4 for IC2 classic, I should have one or I've missed something, greetings.

**Comment by TheDarkDnKTv** [comment]
Copying my asnwer from #127 
`This mod is developed for IC2Exp, IC2Classic not supported.`

If somebody will make and push that chages - i do not mind, but it will cost for me lot of time to support two forks of same mod.
