### ISSUE TITLE
Can't load with GregTech5

### ISSUE THREAD

**Issue by 2sdk** [Nukepowered/GregTech4#170]
[17:42:51] [Client thread/WARN] [GregTech/gregtech_addon]: WRONG ORE DICTIONARY NAMES DETECTED FOR PREFIX: null
[fml-client-latest.log](https://github.com/Nukepowered/GregTech4/files/9386655/fml-client-latest.log)

**Comment by DrParadox7** [comment]
I'm pretty sure you're not meant to mix and match gregtechs.
With the growing epidemic of overgreggified instances this mod is killing, it should come with a warning label.

![image](https://user-images.githubusercontent.com/47131096/185747440-1f7dacf3-bd9c-41e2-bab6-81c93dcdad92.png)

**Comment by 2sdk** [comment]
> I'm pretty sure you're not meant to mix and match gregtechs. With the growing epidemic of overgreggified instances this mod is killing, it should come with a warning label.
> 
> ![image](https://user-images.githubusercontent.com/47131096/185747440-1f7dacf3-bd9c-41e2-bab6-81c93dcdad92.png)

I solved that problem myself and now GregTech4 is loaded with 5 and 6
![MIF@{78VH9@EVXESPUCFUBA](https://user-images.githubusercontent.com/35525171/185868211-16de0a9e-eec2-4e49-a7d9-ac7b0c16465a.png)

**Comment by TheDarkDnKTv** [comment]
Wow, congrads then.
But we still will not provide support with other versions of GT.
