### ISSUE TITLE
GT4 breaks balance with sticks

### ISSUE THREAD

**Issue by DrParadox7** [Nukepowered/GregTech4#173]
Before we would get 4 sticks from 2 planks in Minecraft.

Now GT4 needlessly buffs that by a whole 25%! /s
![image](https://user-images.githubusercontent.com/47131096/188270635-7616c780-0d14-437b-9540-f1d51f9c7acb.png)

This has been occurring since version 4.15.32 and I see no mention of this game breaking mechanic in the changelogs:
https://github.com/Nukepowered/GregTech4/releases/tag/4.15.32

It's probably something to do with the saw recipes:
![image](https://user-images.githubusercontent.com/47131096/188272319-e9443a53-9f87-44d0-b547-189afac85436.png)

**Comment by YuRaNnNzZZ** [comment]
https://github.com/Nukepowered/GregTech4/blob/dcb95af00ea229bfd322c95c68dbafb6314cf15d/src/main/java/gregtechmod/GT_Mod.java#L775-L778

The second `tStack` definition is reusing the first one, which has size of 5 to account the saw buff with wood crafting nerf option disabled.
