### ISSUE TITLE
Consumption of invalid matirial in furnace

### ISSUE THREAD

**Issue by TheDarkDnKTv** [Nukepowered/GregTech4#178]
Maybe invalid metadata check, since was used meta item as input.
https://youtu.be/28lJCofSJvw

**Comment by karmaBonfire** [comment]
Suggested fix: #179

**Comment by karmaBonfire** [comment]
I have played around and found out:
- it is reproducible in steam furnaces as well;
- it doesn't seem like metadata issue: different materials are also affected by this (putting dark ashes and vanilla pork together works too)

**Comment by karmaBonfire** [comment]
Also #137 might be related

**Comment by TheDarkDnKTv** [comment]
The problem is taking effect only at E-Furnace
