### ISSUE TITLE
Bug with universal fluid cell.

### ISSUE THREAD

**Issue by Pilad** [Nukepowered/GregTech4#180]
Если в аутпут хэтч помещать несколько универскальных капсул за раз, то не происходит опустошения.
Если по одной, то опустошает. С обычными капсулами такого не наблюдается.
![изображение](https://user-images.githubusercontent.com/9840821/219847003-d901e2d6-7d42-446e-b11d-e4eb29523240.png)

**Comment by TheDarkDnKTv** [comment]
На сколько я помню, проблема была в самом IC2, ща перепроверю, если так - закрою.

**Comment by Pilad** [comment]
> На сколько я помню, проблема была в самом IC2, ща перепроверю, если так - закрою.

В гт5 такого нет. Хэтчи работают штатно с капсулами.

**Comment by TheDarkDnKTv** [comment]
Класс `ic2.core.item.ItemIC2FluidContainer`
![image](https://user-images.githubusercontent.com/42381105/219847417-03ea59e0-0f86-4b08-82c5-a8386a18d854.png)

Проверил по дебаггеру. 

Почитав код, согласен, что имеет смысл переписать, но билд сами сделаете, ибо из-за одного малозначительного бага делать релиз не стану.

**Comment by Pilad** [comment]
> Класс `ic2.core.item.ItemIC2FluidContainer` ![image](https://user-images.githubusercontent.com/42381105/219847417-03ea59e0-0f86-4b08-82c5-a8386a18d854.png)
> 
> Проверил по дебаггеру.
> 
> Почитав код, согласен, что имеет смысл переписать, но билд сами сделаете, ибо из-за одного малозначительного бага делать релиз не стану.

Главное пофиксить. Потом с новым релизом и выйдет.
