### ISSUE TITLE
The generator takes a long time to restart.

### ISSUE THREAD

**Issue by Pilad** [Nukepowered/GregTech4#181]
Если поставить дизельный генератор, рядом потребитель и он пропадёт в процессе работы генератора при взрыве или если его сбить в креативе, то дизельный генератор замирает и перестаёт работать. Потом возвращаем потребитель и генератор запустится только спустя какое-то время. Думает несколько секунд перед стартом. Может стоит время опроса ему поднять? Чтоб его быстрее отпускало.

**Comment by TheDarkDnKTv** [comment]
![image](https://user-images.githubusercontent.com/42381105/219848494-006aff89-0f30-4f74-aff1-957974bbded4.png)
Да, потому что это сделанно в целях уменьшения бесполезного тика, изменять в основе я это не буду, если у вас проблемы с таймингами и речеком - можете пофиксить в своём форке. 

P.S данная операция триггерит поиск рецепта, который долговат, по этому он везде кешируеться, либо проверяеться при апдейте блока из вне/инвентаря.
