### ISSUE TITLE
Helium plasma cell.

### ISSUE THREAD

**Issue by Pilad** [Nukepowered/GregTech4#182]
У гелиевой плазмы нет капсул. Транспортировать только напрямую посредством труб в плазмоген. Может вернуть капсулы?

**Comment by TheDarkDnKTv** [comment]
Они есть, их просто нет в NEI почему-то, и честно - не особо важно почему.
![image](https://user-images.githubusercontent.com/42381105/219847971-3b705c93-1634-4122-86de-e04c7aceb512.png)

**Comment by Pilad** [comment]
> Они есть, их просто нет в NEI почему-то, и честно - не особо важно почему. ![image](https://user-images.githubusercontent.com/42381105/219847971-3b705c93-1634-4122-86de-e04c7aceb512.png)

Впринципе согласен. Главное чтоб можно было налить плазму в любую наполняющую машину или инпут или аутпут хэтч и наполнить капсулу.
