### ISSUE TITLE
Do not pour fuel into capsules in a diesel or other generator.

### ISSUE THREAD

**Issue by Pilad** [Nukepowered/GregTech4#183]
Если залить топливо в дизель или иной генератор , то капсулами нельзя вылить обратно топливо. Не универсальной, не обычной не выливается. В Гт5 так можно делать. Опустошать буффер машины обратно.
![изображение](https://user-images.githubusercontent.com/9840821/219847737-9e349f13-ce35-4410-889d-f9ac50d458c6.png)

**Comment by TheDarkDnKTv** [comment]
Потому что тут ясно написанно IN-OUT, это не ГТ5, а ГТ4. Его функционал в большей степени придерживаеться именно ГТ4.

**Comment by Pilad** [comment]
> Потому что тут ясно написанно IN-OUT, это не ГТ5, а ГТ4. Его функционал в большей степени придерживаеться именно ГТ4.

В зашел в гт4 на 1.6.4 - тут это так же работает прекрасно.Наполняют генераторы из своего буффера капсулы.
![изображение](https://user-images.githubusercontent.com/9840821/219848730-06e2c7d3-10f3-493e-8920-913d60900cde.png)

**Comment by Pilad** [comment]
> Потому что тут ясно написанно IN-OUT, это не ГТ5, а ГТ4. Его функционал в большей степени придерживаеться именно ГТ4.

Раз говоришь функционал гт4 поддерживает, то пофикси. В гт4 это пашет.
