### ISSUE TITLE
The semi-liquid generator does not burn liquid lithium.

### ISSUE THREAD

**Issue by Pilad** [Nukepowered/GregTech4#184]
Жидкий литий не сгорает
![изображение](https://user-images.githubusercontent.com/9840821/219848563-9fa9918f-c158-4774-aa9b-bd3c96b119ad.png)
В неи рецепт для создания жидкого лития
![изображение](https://user-images.githubusercontent.com/9840821/219848585-e1772abd-ce06-4fbd-aa62-c3c004013a17.png)
Рецепт в полужидкостном генераторе
![изображение](https://user-images.githubusercontent.com/9840821/219848613-f77446db-5676-462e-8ff7-5e2e61a254bf.png)
При этом твердый литий горит прекрасно
![изображение](https://user-images.githubusercontent.com/9840821/219848631-8149bf1a-47df-477d-8ac5-fb9898064064.png)

**Comment by TheDarkDnKTv** [comment]
After check on version v416.44, recipe seems working fine
![image](https://github.com/Nukepowered/GregTech4/assets/42381105/d6aa9d6f-cb08-4268-8b7f-2b387829cf03)
![image](https://github.com/Nukepowered/GregTech4/assets/42381105/f343ccf2-1da7-4ded-ad9c-d67a4336eee3)
