### ISSUE TITLE
Crash on startup: Found non-valid stack on output items: 'null', idx: 1

### ISSUE THREAD

**Issue by aking4125** [Nukepowered/GregTech4#185]
Hello,

Upon adding this mod to our pack, the client crashes during startup with the following crash report: 

[crash-2023-02-27_07.25.06-client.txt](https://github.com/Nukepowered/GregTech4/files/10839737/crash-2023-02-27_07.25.06-client.txt)

Any ideas?

**Comment by TheDarkDnKTv** [comment]
You have a material from GT registery present in other mod, but that mod does not have some variant required for GT processing, probably. I can suggest removing mods one by one to define which one contains ingot/dust processed, then disabling material processing from this mod one by one in `DynamicConfig.cfg`

P.S According on the code, it is `extruder` recipe for some metal ingot present in GT Materials (you can find names in (enum)[src/main/java/gregtechmod/api/enums/Materials.java])

**Comment by TheDarkDnKTv** [comment]
Actually I just noticed that we does not have this config category in config, so probably I need your help to define mod and then ingot to exlude it from generation, since this material suppouse to generate GT gears from ingot, but gears itself not present it is reason of crash.

**Comment by aking4125** [comment]
We'll look into it, though we have a lot of mods to shuffle through. But since it's a recipe related to the extruder that might narrow it down a bit?

**Comment by TheDarkDnKTv** [comment]
As I said it is metal ingot material that is suppouse have gears in GT... but does not. Look through Materials in link I provided before, and search for all Materials that has `|128` flag in it (search in browser), and probably it is not suppouse to have `|4` flag.

The final item will have ore dictionary name `ingotX` where X is material from that file.

**Comment by CrossVas** [comment]
Magic, Force and Diamond are the one that have both 4 and 128.
