### ISSUE TITLE
recipe missing

### ISSUE THREAD

**Issue by meowNIman** [Nukepowered/GregTech4#189]
Для выхода в масератор внутри самого мода не используя сторонние машинки необходима пыль лазурита ( для адванснутых чипов)
которую невозможно получить без масератора

отсутствует рецепт пыли лазурита с помощью iron mortar
или возможноти выбить ее из руды лазурита молотком как на новых версиях гт
( альтернативный рецепт пыли через центрифугу тоже щаблокирован улучшенным чипом в рецепте

**Comment by meowNIman** [comment]
единственный способ - скрп боксы

**Comment by YuRaNnNzZZ** [comment]
![2023-06-04_01-35-46_e05752b3-77dd-4bde-b20f-027c088416b3](https://github.com/Nukepowered/GregTech4/assets/5104603/410bd3cc-1299-45bc-bce8-d1999442beef)
![2023-06-04_01-35-56_8851e83d-7448-4c61-ae85-03c0ece78398](https://github.com/Nukepowered/GregTech4/assets/5104603/bfaa31bd-e585-4bd2-9c7a-423fc7e8cade)

**Comment by meowNIman** [comment]
> ![2023-06-04_01-35-46_e05752b3-77dd-4bde-b20f-027c088416b3](https://user-images.githubusercontent.com/5104603/243137121-410bd3cc-1299-45bc-bce8-d1999442beef.png) ![2023-06-04_01-35-56_8851e83d-7448-4c61-ae85-03c0ece78398](https://user-images.githubusercontent.com/5104603/243137122-bfaa31bd-e585-4bd2-9c7a-423fc7e8cade.png)

oh
u right
my nei didnt show this recipe 
and i thought all the steam machines had steam in fron of their name

**Comment by Pilad** [comment]
Да любой дробитель должен подробить.
