### ISSUE TITLE
Right click on GT Tiles triggers both block placing and block interaction 

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#190]
After update, clicking on every GT tile triggers both block placing and interaction (opening gui)
I've checked the code and it seems that there is a missing return statement for **onBlockActivated** in [GT_BlockMetaID_Machine](https://github.com/Nukepowered/GregTech4/blob/c220c316288eceacf8a20134decb0e03dc8789bd/src/main/java/gregtechmod/common/blocks/GT_BlockMetaID_Machine.java#L659)

Adding **return true;** between [L670](https://github.com/Nukepowered/GregTech4/blob/c220c316288eceacf8a20134decb0e03dc8789bd/src/main/java/gregtechmod/common/blocks/GT_BlockMetaID_Machine.java#LL670C5-L670C5) and [L671](https://github.com/Nukepowered/GregTech4/blob/c220c316288eceacf8a20134decb0e03dc8789bd/src/main/java/gregtechmod/common/blocks/GT_BlockMetaID_Machine.java#L671) fixes the issue.

Thanks!

**Comment by DrParadox7** [comment]
This commit breaks right click with Gregtech blocks:
Gif: https://www.mediafire.com/file/4ogwmzl4ueffe0s/RightClicking.gif/file

You might want to revert it and reopen this issue.
