### ISSUE TITLE
Your base package name is inconsistent with official GregTech

### ISSUE THREAD

**Issue by alikindsys** [Nukepowered/GregTech4#198]
Official GT's package name is `gregtech` and yours is `gregtechmod`.

I have no idea if thats by design but this is causing crashes with other mods.

That causes all addons like [`CropsPP`](
https://github.com/bartimaeusnek/crops-plus-plus/) to crash due to a `ClassNotFoundException`, which is totally reasonable since that class just doesn't exist, as far as both the GT addons and java are concerned.

List of addons that I could find that were affected
---
1 - :warning: :x: CropsPP
**Reproduction:** 
- Place any vanilla sapling into a IC2 Crop.
- Right Click at any stage of growth.

**Code path:**  
```java
// com.github.bartimaeusnek.cropspp.crops.cpp.Bonsais.java
@Override
public ItemStack getGain(ICropTile iCropTile) {
        int max = 0;
        for (int chanch : chanches) {
            max=Math.max(chanch,max);
        }
        // ClassNotFoundException: gregtech.api.objects.XSTR
        XSTR rand = new XSTR();
        
        int roll = rand.nextInt(max);
        for (int i = chanches.length - 1; i >= 0; i--) {
```
This one is specially worse, since the `XSTR` class doesn't exist on the project, so even if there were a way to redirect the call to your mod, it would fail.

**Comment by alikindsys** [comment]
It is of note that I was going to publish that on the [Lost Era Modpack's Issue Tracker](https://github.com/DrParadox7/Lost-Era-Modpack/issues) but since this a problem that involved a cross-mod compatibility issue that's more technical I've decided to put it here instead.

**Comment by TheDarkDnKTv** [comment]
The package name of GT 4 was originally `gregtechmod` and you can check it at 1.6.4 version that been ported.
Seems addon is intended to work with GT5, not GT4.
Try reporting to addon dev tracker instead.
