### ISSUE TITLE
ores do not render properly when not touching stone

### ISSUE THREAD

**Issue by lawleagle** [Nukepowered/GregTech4#200]
![image](https://github.com/user-attachments/assets/f601d797-04ed-4a17-ad75-197ac9ee18cb)
same ore, `Pyrite Ore` and `Bauxite Ore`, on the top placed on dirt, on the bottom placed on stone.

hidden ores disabled in config, but this happens with hidden ores enabled too

**Comment by lawleagle** [comment]
![image](https://github.com/user-attachments/assets/124c4098-253c-410e-8f70-db3762eafc5d)
in-world generation

**Comment by TheDarkDnKTv** [comment]
Its not a inproper render, it's been intended as ore using neighbour _stone_ texture, like endstone and netherrack.
